import type { ExecArgs } from "@medusajs/framework/types"
import { HOP_MODULE } from "../modules/hop"

type HopEntry = {
  name: string
  slug: string
  origin: string
  country_code: string
  breeder: string
  available_forms: string[]
  farm_notes: string
  flavor_profile: string
  description?: string
}

const HOPS: HopEntry[] = [
  // ── United States ──────────────────────────────────────────────────────────
  {
    name: "Citra",
    slug: "citra",
    origin: "USA - Yakima Valley",
    country_code: "US",
    breeder: "Indie Hops / HBC",
    available_forms: ["T90", "Cryo", "Incognito", "Spectrum", "HyperBoost", "DynaBoost", "CGX"],
    farm_notes:
      "Crosby Hops (Oregon) offer Estate Grown Citra lots. Yakima Chief Hops distribute Cryo, HyperBoost, and DynaBoost formats.",
    flavor_profile: "Tropical, citrus, grapefruit, passionfruit",
  },
  {
    name: "Mosaic",
    slug: "mosaic",
    origin: "USA - Yakima Valley",
    country_code: "US",
    breeder: "HBC",
    available_forms: ["T90", "Cryo", "Incognito", "Spectrum", "HyperBoost", "DynaBoost"],
    farm_notes:
      "HBC (Hop Breeding Company — YCH + BarthHaas JV). All advanced forms distributed via Yakima Chief Hops.",
    flavor_profile: "Berry, tropical, herbal, earthy",
  },
  {
    name: "Simcoe",
    slug: "simcoe",
    origin: "USA - Yakima Valley",
    country_code: "US",
    breeder: "Select Botanicals / ADHA",
    available_forms: ["T90", "Cryo", "HyperBoost"],
    farm_notes: "Trademarked by Select Botanicals Group. Grown across Yakima Valley farms.",
    flavor_profile: "Pine, citrus, earthy, passionfruit",
  },
  {
    name: "El Dorado",
    slug: "el-dorado",
    origin: "USA - Washington",
    country_code: "US",
    breeder: "Brewing & Hop Science",
    available_forms: ["T90", "Cryo", "LiquidLupulin"],
    farm_notes: "Bred by Brewing & Hop Science LLC, grown in Moxee, WA.",
    flavor_profile: "Tropical, stone fruit, candy, watermelon",
  },
  {
    name: "Idaho 7",
    slug: "idaho-7",
    origin: "USA - Idaho",
    country_code: "US",
    breeder: "Jackson Hop Farm",
    available_forms: ["T90", "Cryo"],
    farm_notes: "Grown by Jackson Hop Farm in Wilder, Idaho.",
    flavor_profile: "Stone fruit, tropical, pine, black tea",
  },
  {
    name: "Strata",
    slug: "strata",
    origin: "USA - Oregon",
    country_code: "US",
    breeder: "Indie Hops",
    available_forms: ["T90", "HyperBoost"],
    farm_notes: "Indie Hops proprietary variety (released 2019). Previously known as Rawlings.",
    flavor_profile: "Passionfruit, cannabis, strawberry, dank",
  },
  {
    name: "Cascade",
    slug: "cascade",
    origin: "USA - Oregon / Washington",
    country_code: "US",
    breeder: "USDA",
    available_forms: ["T90", "Cryo", "CGX", "WholeCone"],
    farm_notes:
      "Classic American hop released 1972. Crosby Hops grow an Estate Grown Cascade and also offer the CGX cryogenic pellet format.",
    flavor_profile: "Floral, citrus, grapefruit, spicy",
  },
  {
    name: "Centennial",
    slug: "centennial",
    origin: "USA - Yakima Valley",
    country_code: "US",
    breeder: "USDA",
    available_forms: ["T90", "DynaBoost"],
    farm_notes: "Released by USDA in 1990. Crosby Hops offer estate-grown Centennial.",
    flavor_profile: "Floral, citrus, lemon",
  },
  {
    name: "Amarillo",
    slug: "amarillo",
    origin: "USA - Washington",
    country_code: "US",
    breeder: "Virgil Gamache Farms",
    available_forms: ["T90", "Cryo", "CGX"],
    farm_notes:
      "Proprietary to Virgil Gamache Farms, Toppenish, WA. Crosby Hops offer Estate Grown Amarillo CGX.",
    flavor_profile: "Orange, floral, tropical, grapefruit",
  },
  {
    name: "Chinook",
    slug: "chinook",
    origin: "USA - Washington",
    country_code: "US",
    breeder: "USDA",
    available_forms: ["T90", "Incognito", "WholeCone"],
    farm_notes: "Released by USDA in 1985. Crosby Hops offer estate-grown Chinook.",
    flavor_profile: "Pine, grapefruit, spicy",
  },
  {
    name: "Columbus",
    slug: "columbus",
    origin: "USA - Washington",
    country_code: "US",
    breeder: "Yakima Chief Hops",
    available_forms: ["T90", "Cryo"],
    farm_notes:
      "Also known as CTZ (Columbus/Tomahawk/Zeus) due to trademark overlap. High alpha dual-purpose variety.",
    flavor_profile: "Herbal, earthy, spicy, dank",
  },
  {
    name: "Loral",
    slug: "loral",
    origin: "USA - Yakima Valley",
    country_code: "US",
    breeder: "John I. Haas",
    available_forms: ["T90"],
    farm_notes: "John I. Haas proprietary variety, released 2016.",
    flavor_profile: "Floral, citrus, pepper, dark fruit",
  },
  {
    name: "Dolcita",
    slug: "dolcita",
    origin: "USA - Yakima Valley",
    country_code: "US",
    breeder: "John I. Haas",
    available_forms: ["T90", "Incognito"],
    farm_notes: "John I. Haas proprietary. Available in Incognito extract form.",
    flavor_profile: "Mild, herbal, stone fruit, apricot",
  },
  {
    name: "Sabro",
    slug: "sabro",
    origin: "USA - New Mexico",
    country_code: "US",
    breeder: "HBC",
    available_forms: ["T90", "Cryo", "DynaBoost", "HyperBoost"],
    farm_notes: "HBC 438. Bred at New Mexico State University from a spontaneous hop.",
    flavor_profile: "Coconut, tangerine, tropical, mint",
  },
  {
    name: "Comet",
    slug: "comet",
    origin: "USA - Oregon",
    country_code: "US",
    breeder: "USDA",
    available_forms: ["T90", "CGX"],
    farm_notes:
      "Vintage USDA variety from 1974, rediscovered by craft brewers. Crosby Hops is the primary estate-grown supplier.",
    flavor_profile: "Citrus, grapefruit, tropical, pine",
  },
  {
    name: "Azacca",
    slug: "azacca",
    origin: "USA - Washington",
    country_code: "US",
    breeder: "ADHA",
    available_forms: ["T90", "Spectrum"],
    farm_notes:
      "ADHA (American Dwarf Hop Association) variety. Named after the Haitian god of agriculture.",
    flavor_profile: "Tropical, mango, pineapple, citrus",
  },
  {
    name: "Ekuanot",
    slug: "ekuanot",
    origin: "USA - Yakima Valley",
    country_code: "US",
    breeder: "HBC",
    available_forms: ["T90", "Cryo", "Incognito"],
    farm_notes: "HBC 366. Released 2014. Available in Incognito extract form.",
    flavor_profile: "Berry, citrus, watermelon, papaya",
  },
  {
    name: "Krush",
    slug: "krush",
    origin: "USA - Yakima Valley",
    country_code: "US",
    breeder: "Indie Hops",
    available_forms: ["T90", "HyperBoost"],
    farm_notes:
      "Indie Hops proprietary. Also known as HBC 586. Bred for high thiol-releasing potential.",
    flavor_profile: "Berry, citrus, stone fruit, tropical",
  },
  {
    name: "Pacific Sunrise",
    slug: "pacific-sunrise",
    origin: "USA - Yakima Valley",
    country_code: "US",
    breeder: "HBC",
    available_forms: ["T90"],
    farm_notes: "HBC variety. Limited commercial availability.",
    flavor_profile: "Tropical, stone fruit, white wine",
  },
  {
    name: "Warrior",
    slug: "warrior",
    origin: "USA - Yakima Valley",
    country_code: "US",
    breeder: "Yakima Chief Ranches",
    available_forms: ["T90"],
    farm_notes: "YCR 5. Selected for clean bittering and low cohumulone.",
    flavor_profile: "Clean bittering, mild citrus, resinous",
  },
  {
    name: "Nugget",
    slug: "nugget",
    origin: "USA - Oregon",
    country_code: "US",
    breeder: "USDA",
    available_forms: ["T90", "WholeCone"],
    farm_notes: "Released by USDA in 1982. High alpha bittering variety.",
    flavor_profile: "Herbal, spicy, heavy bittering",
  },
  {
    name: "Talus",
    slug: "talus",
    origin: "USA - Idaho",
    country_code: "US",
    breeder: "HBC",
    available_forms: ["T90"],
    farm_notes: "HBC 692. Released 2022. Grown in Idaho.",
    flavor_profile: "Pink guava, coconut, tropical, citrus",
  },
  {
    name: "Cashmere",
    slug: "cashmere",
    origin: "USA - Washington",
    country_code: "US",
    breeder: "Washington State University",
    available_forms: ["T90"],
    farm_notes: "Washington State University breeding program, released 2017.",
    flavor_profile: "Melon, lemon, lime, herbal",
  },
  {
    name: "HBC 586",
    slug: "hbc-586",
    origin: "USA - Yakima Valley",
    country_code: "US",
    breeder: "HBC",
    available_forms: ["T90"],
    farm_notes: "HBC experimental designation. Same as Krush® once commercially named.",
    flavor_profile: "Coconut, tropical, sweet fruit",
  },
  {
    name: "HBC 472",
    slug: "hbc-472",
    origin: "USA - Yakima Valley",
    country_code: "US",
    breeder: "HBC",
    available_forms: ["T90"],
    farm_notes: "HBC experimental variety. Limited commercial release.",
    flavor_profile: "Stone fruit, melon, tropical",
  },
  {
    name: "Sultana",
    slug: "sultana",
    origin: "USA - Washington",
    country_code: "US",
    breeder: "Washington State University",
    available_forms: ["T90"],
    farm_notes: "WSU breeding program. Formerly known as Experimental #05256.",
    flavor_profile: "Pineapple, tangerine, apricot",
  },
  {
    name: "Triumph",
    slug: "triumph",
    origin: "USA - Yakima Valley",
    country_code: "US",
    breeder: "Hopsteiner",
    available_forms: ["T90"],
    farm_notes: "Hopsteiner proprietary. Released 2020.",
    flavor_profile: "Stone fruit, citrus, floral",
  },
  {
    name: "Lotus",
    slug: "lotus",
    origin: "USA - Washington",
    country_code: "US",
    breeder: "Indie Hops",
    available_forms: ["T90"],
    farm_notes: "Indie Hops proprietary variety.",
    flavor_profile: "Orange, vanilla, tropical",
  },
  {
    name: "Bru-1",
    slug: "bru-1",
    origin: "USA - Michigan",
    country_code: "US",
    breeder: "Michigan State University",
    available_forms: ["T90", "Spectrum"],
    farm_notes: "Michigan State University breeding program. Available in Spectrum extract form.",
    flavor_profile: "Stone fruit, pineapple, tropical",
  },
  {
    name: "Peacharine",
    slug: "peacharine",
    origin: "USA / New Zealand",
    country_code: "US",
    breeder: "Experimental",
    available_forms: ["T90"],
    farm_notes:
      "Rare experimental variety. Seen in Fidens Brewing and Lolev releases. Limited commercial supply.",
    flavor_profile: "Peach, nectarine, stone fruit, tropical",
  },

  // ── New Zealand ────────────────────────────────────────────────────────────
  {
    name: "Nelson Sauvin",
    slug: "nelson-sauvin",
    origin: "New Zealand - Nelson",
    country_code: "NZ",
    breeder: "NZ Hops Ltd",
    available_forms: ["T90", "Cryo", "SubZeroHopKief", "HopKief"],
    farm_notes:
      "NZ Hops Ltd holds the trademark. Freestyle Hops offer the Bliss Process T90 and SubZero Hop Kief versions. Eggers Hops (Upper Moutere) provide farm-specific lots. Maui Hops grow a Hawaii-terroir variant.",
    flavor_profile: "White wine, gooseberry, grapefruit",
  },
  {
    name: "Riwaka",
    slug: "riwaka",
    origin: "New Zealand - Motueka Valley",
    country_code: "NZ",
    breeder: "NZ Hops Ltd",
    available_forms: ["T90", "Cryo", "SubZeroHopKief", "HopKief"],
    farm_notes:
      "Eggers Hops (Upper Moutere, NZ) specialise in Riwaka — 6-generation family farm, direct-to-brewer. Freestyle Hops also supply T90 and SubZero Hop Kief versions.",
    flavor_profile: "Passionfruit, grapefruit, citrus",
  },
  {
    name: "Motueka",
    slug: "motueka",
    origin: "New Zealand - Nelson",
    country_code: "NZ",
    breeder: "NZ Hops Ltd",
    available_forms: ["T90", "SubZeroHopKief", "HyperBoost", "CGX"],
    farm_notes:
      "NZ Hops Ltd standard supply. Freestyle Hops offer Mega Motueka (selected high-aroma lots) and SubZero Hop Kief. Also available as CGX from Crosby Hops.",
    flavor_profile: "Tropical, lime, lemon zest",
  },
  {
    name: "Moutere",
    slug: "moutere",
    origin: "New Zealand - Nelson",
    country_code: "NZ",
    breeder: "Freestyle Hops",
    available_forms: ["T90"],
    farm_notes:
      "Freestyle Hops exclusive lot designation — selected variety grown in the Moutere/Upper Moutere region of the Nelson/Tasman district.",
    flavor_profile: "Stone fruit, lime, tropical, pine",
  },
  {
    name: "Kohia Nelson",
    slug: "kohia-nelson",
    origin: "New Zealand - Nelson",
    country_code: "NZ",
    breeder: "Freestyle Hops",
    available_forms: ["T90", "HopKief"],
    farm_notes:
      "Proprietary Freestyle Hops variety — a Nelson Sauvin cross bred specifically for their Kohia Nelson T90 and Hop Kief products.",
    flavor_profile: "White wine, tropical, gooseberry",
  },
  {
    name: "Wakatu",
    slug: "wakatu",
    origin: "New Zealand - Nelson",
    country_code: "NZ",
    breeder: "NZ Hops Ltd",
    available_forms: ["T90", "SubZeroHopKief"],
    farm_notes: "NZ Hops Ltd variety. Triploid derived from Hallertau Mittelfrüh.",
    flavor_profile: "Floral, lime, lemon, tropical",
  },
  {
    name: "Green Bullet",
    slug: "green-bullet",
    origin: "New Zealand",
    country_code: "NZ",
    breeder: "NZ Hops Ltd",
    available_forms: ["T90", "HopKief", "SubZeroHopKief"],
    farm_notes:
      "NZ Hops Ltd dual-purpose variety. Freestyle Hops offer Green Bullet Hop Kief and SubZero Hop Kief.",
    flavor_profile: "Earthy, pine, resinous, spicy",
  },
  {
    name: "Southern Cross",
    slug: "southern-cross",
    origin: "New Zealand",
    country_code: "NZ",
    breeder: "NZ Hops Ltd",
    available_forms: ["T90", "SubZeroHopKief"],
    farm_notes: "NZ Hops Ltd dual-purpose variety. Freestyle Hops offer SubZero Hop Kief.",
    flavor_profile: "Pine, lemon, spicy, citrus",
  },
  {
    name: "Rakau",
    slug: "rakau",
    origin: "New Zealand",
    country_code: "NZ",
    breeder: "NZ Hops Ltd",
    available_forms: ["T90", "HopKief"],
    farm_notes: "NZ Hops Ltd variety. Freestyle Hops offer Rakau Hop Kief.",
    flavor_profile: "Stone fruit, apricot, fig, pine",
  },
  {
    name: "Wai-iti",
    slug: "wai-iti",
    origin: "New Zealand - Nelson",
    country_code: "NZ",
    breeder: "NZ Hops Ltd",
    available_forms: ["T90"],
    farm_notes: "NZ Hops Ltd variety, released 2011. Named after the Wai-iti River.",
    flavor_profile: "Lime, mandarin, floral, peach",
  },
  {
    name: "Pacific Jade",
    slug: "pacific-jade",
    origin: "New Zealand - Nelson",
    country_code: "NZ",
    breeder: "NZ Hops Ltd",
    available_forms: ["T90"],
    farm_notes: "NZ Hops Ltd variety. Cross of First Choice and New Zealand Hallertau.",
    flavor_profile: "Cedar, citrus, fresh, herbal",
  },
  {
    name: "Waimea",
    slug: "waimea",
    origin: "New Zealand",
    country_code: "NZ",
    breeder: "NZ Hops Ltd",
    available_forms: ["T90"],
    farm_notes: "NZ Hops Ltd dual-purpose variety with very high alpha acid content.",
    flavor_profile: "Tangerine, pine, tropical, citrus",
  },
  {
    name: "Kohatu",
    slug: "kohatu",
    origin: "New Zealand",
    country_code: "NZ",
    breeder: "NZ Hops Ltd",
    available_forms: ["T90"],
    farm_notes: "NZ Hops Ltd variety. Named after the Māori word for stone.",
    flavor_profile: "Tropical, pine needle, fresh cut grass",
  },
  {
    name: "Phantasm",
    slug: "phantasm",
    origin: "New Zealand",
    country_code: "NZ",
    breeder: "NZ Hops Ltd",
    available_forms: ["T90"],
    farm_notes:
      "NZ Hops Ltd. High-thiol variety, prized for releasing tropical aromas during fermentation.",
    flavor_profile: "Thiol-releasing, tropical, passionfruit",
  },

  // ── Australia ──────────────────────────────────────────────────────────────
  {
    name: "Galaxy",
    slug: "galaxy",
    origin: "Australia - Victoria / Tasmania",
    country_code: "AU",
    breeder: "HPA",
    available_forms: ["T90", "Cryo", "LiquidLupulin", "Spectrum"],
    farm_notes:
      "HPA (Hop Products Australia) holds the Galaxy trademark. Grown in Tasmania and Victoria. Available in Liquid Lupulin (older YCH Cryo-equivalent) and Spectrum extract forms.",
    flavor_profile: "Passionfruit, peach, citrus, tropical",
  },
  {
    name: "Vic Secret",
    slug: "vic-secret",
    origin: "Australia - Victoria",
    country_code: "AU",
    breeder: "HPA",
    available_forms: ["T90", "Spectrum"],
    farm_notes: "HPA proprietary variety, grown in Victoria. Available in Spectrum extract form.",
    flavor_profile: "Pineapple, pine, passionfruit, herbs",
  },
  {
    name: "Eclipse",
    slug: "eclipse",
    origin: "Australia - Victoria",
    country_code: "AU",
    breeder: "HPA",
    available_forms: ["T90", "LiquidLupulin"],
    farm_notes: "HPA proprietary. Available in Liquid Lupulin (YCH-processed) form.",
    flavor_profile: "Tropical, resinous, citrus",
  },
  {
    name: "Nectaron",
    slug: "nectaron",
    origin: "Australia",
    country_code: "AU",
    breeder: "HPA",
    available_forms: ["T90"],
    farm_notes:
      "HPA proprietary. Released approximately 2019. Known for extremely high oil content and intense tropical aromatics.",
    flavor_profile: "Pineapple, stone fruit, grapefruit, tropical",
  },
  {
    name: "Topaz",
    slug: "topaz",
    origin: "Australia - Tasmania",
    country_code: "AU",
    breeder: "HPA",
    available_forms: ["T90"],
    farm_notes: "HPA proprietary. Dual-purpose variety grown in Tasmania.",
    flavor_profile: "Lychee, citrus, resinous",
  },
  {
    name: "Enigma",
    slug: "enigma",
    origin: "Australia - Tasmania",
    country_code: "AU",
    breeder: "HPA",
    available_forms: ["T90"],
    farm_notes: "HPA proprietary. Grown in Tasmania.",
    flavor_profile: "Redcurrant, raspberry, wine, pine",
  },
  {
    name: "Ella",
    slug: "ella",
    origin: "Australia - Tasmania",
    country_code: "AU",
    breeder: "HPA",
    available_forms: ["T90"],
    farm_notes: "HPA proprietary, formerly known as Stella. Grown in Tasmania.",
    flavor_profile: "Spicy, floral, anise, grapefruit",
  },
  {
    name: "Summer",
    slug: "summer",
    origin: "Australia - Tasmania",
    country_code: "AU",
    breeder: "HPA",
    available_forms: ["T90"],
    farm_notes: "HPA proprietary. Grown in Tasmania.",
    flavor_profile: "Apricot, melon, citrus",
  },
  {
    name: "Helga",
    slug: "helga",
    origin: "Australia - Tasmania",
    country_code: "AU",
    breeder: "HPA",
    available_forms: ["T90"],
    farm_notes: "HPA proprietary. Also known as Southern Hallertau. Grown in Tasmania.",
    flavor_profile: "Floral, herbal, delicate",
  },
  {
    name: "Superdelic",
    slug: "superdelic",
    origin: "Australia - Tasmania",
    country_code: "AU",
    breeder: "HPA",
    available_forms: ["T90"],
    farm_notes: "HPA proprietary. High-alpha aroma variety from Tasmania.",
    flavor_profile: "Tropical, mango, guava",
  },

  // ── Europe ─────────────────────────────────────────────────────────────────
  {
    name: "Hallertau Blanc",
    slug: "hallertau-blanc",
    origin: "Germany - Bavaria",
    country_code: "EU",
    breeder: "Hüll Research Institute",
    available_forms: ["T90"],
    farm_notes: "Bred at Hüll Hop Research Institute (HVG), Bavaria. Released 2012.",
    flavor_profile: "White wine, gooseberry, lemongrass",
  },
  {
    name: "Hallertau Mittelfruh",
    slug: "hallertau-mittelfruh",
    origin: "Germany - Bavaria",
    country_code: "EU",
    breeder: "Traditional / Hüll",
    available_forms: ["T90", "WholeCone"],
    farm_notes:
      "Classic Bavarian noble hop. Primary growing region is the Hallertau district, Bavaria.",
    flavor_profile: "Floral, spicy, herbal, mild",
  },
  {
    name: "Saaz",
    slug: "saaz",
    origin: "Czech Republic - Bohemia",
    country_code: "EU",
    breeder: "Czech Hop Institute",
    available_forms: ["T90", "WholeCone"],
    farm_notes:
      "Grown in the Žatec (Saaz) region of Bohemia, Czech Republic. One of the four classic noble hops.",
    flavor_profile: "Earthy, spicy, herbal, mild",
  },
  {
    name: "Tettnang",
    slug: "tettnang",
    origin: "Germany - Baden-Württemberg",
    country_code: "EU",
    breeder: "Traditional",
    available_forms: ["T90", "WholeCone"],
    farm_notes: "Noble hop from the Tettnang region, Baden-Württemberg.",
    flavor_profile: "Spicy, herbal, floral, mild",
  },
  {
    name: "Fuggle",
    slug: "fuggle",
    origin: "England - Kent",
    country_code: "EU",
    breeder: "Traditional",
    available_forms: ["T90", "WholeCone"],
    farm_notes: "Classic English hop, first grown by Richard Fuggle in Kent, 1861.",
    flavor_profile: "Earthy, woody, mild, floral",
  },
  {
    name: "East Kent Golding",
    slug: "east-kent-golding",
    origin: "England - Kent",
    country_code: "EU",
    breeder: "Traditional",
    available_forms: ["T90", "WholeCone"],
    farm_notes: "Grown in East Kent, England. Protected Designation of Origin (PDO) status.",
    flavor_profile: "Spicy, floral, honey, earthy",
  },
  {
    name: "Mandarina Bavaria",
    slug: "mandarina-bavaria",
    origin: "Germany - Bavaria",
    country_code: "EU",
    breeder: "Hüll Research Institute",
    available_forms: ["T90"],
    farm_notes: "Bred at Hüll. Released 2012. Named for its mandarin orange character.",
    flavor_profile: "Mandarin, citrus, sweet",
  },
  {
    name: "Huell Melon",
    slug: "huell-melon",
    origin: "Germany - Bavaria",
    country_code: "EU",
    breeder: "Hüll Research Institute",
    available_forms: ["T90"],
    farm_notes: "Bred at Hüll. Released 2012.",
    flavor_profile: "Honeydew melon, strawberry",
  },
  {
    name: "Perle",
    slug: "perle",
    origin: "Germany",
    country_code: "EU",
    breeder: "Hüll Research Institute",
    available_forms: ["T90"],
    farm_notes: "Released 1978 at Hüll. Widely grown in German hop regions.",
    flavor_profile: "Spicy, floral, minty, fruity",
  },
  {
    name: "Magnum",
    slug: "magnum",
    origin: "Germany",
    country_code: "EU",
    breeder: "Hüll Research Institute",
    available_forms: ["T90"],
    farm_notes: "High-alpha bittering hop released at Hüll in 1993.",
    flavor_profile: "Clean bittering, subtle fruit",
  },
  {
    name: "Sorachi Ace",
    slug: "sorachi-ace",
    origin: "Japan - Hokkaido",
    country_code: "EU",
    breeder: "Sapporo Breweries",
    available_forms: ["T90"],
    farm_notes:
      "Bred in 1984 by Sapporo Breweries at the Sorachi experimental hop farm in Hokkaido. Currently grown in the US Pacific Northwest by brewers.",
    flavor_profile: "Lemon, dill, tea, coconut",
  },
]

export default async function seedHops({ container }: ExecArgs) {
  const hopService = container.resolve(HOP_MODULE) as any

  console.log(`[Seed Hops] Upserting ${HOPS.length} hop varieties...`)

  let created = 0
  let updated = 0
  let errors = 0

  for (const hop of HOPS) {
    try {
      const existing = await hopService.listHops({ slug: hop.slug })

      if (existing.length > 0) {
        await hopService.updateHops({
          id: existing[0].id,
          name: hop.name,
          origin: hop.origin,
          country_code: hop.country_code,
          breeder: hop.breeder,
          available_forms: hop.available_forms,
          farm_notes: hop.farm_notes,
          flavor_profile: hop.flavor_profile,
          ...(hop.description ? { description: hop.description } : {}),
          is_active: true,
        })
        updated++
      } else {
        await hopService.createHops({
          name: hop.name,
          slug: hop.slug,
          origin: hop.origin,
          country_code: hop.country_code,
          breeder: hop.breeder,
          available_forms: hop.available_forms,
          farm_notes: hop.farm_notes,
          flavor_profile: hop.flavor_profile,
          ...(hop.description ? { description: hop.description } : {}),
          is_active: true,
        })
        created++
      }
    } catch (err) {
      console.error(
        `[Seed Hops] Error on "${hop.name}": ${err instanceof Error ? err.message : String(err)}`
      )
      errors++
    }
  }

  console.log(`[Seed Hops] Done: ${created} created, ${updated} updated, ${errors} errors.`)
}
